sudo: false
cache:
  directories:
    - "$HOME/.stack/"
matrix:
  include:
    - env: RESOLVER=lts-4
    - env: RESOLVER=lts-5
    - env: RESOLVER=lts-6
    - env: RESOLVER=lts-7
    - env: RESOLVER=lts-8
    - env: RESOLVER=lts-9
    - env: RESOLVER=lts-10
    - env: RESOLVER=lts-11
    - env: RESOLVER=lts-12
    - env: RESOLVER=lts-13
    - env: RESOLVER=nightly
  allow_failures:
    - env: RESOLVER=nightly
addons:
  apt:
    packages:
      - libgmp-dev
      - python3-pip
before_install:
  # stack
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - ./latest $RESOLVER > stack-travis.yaml
  - export STACK_YAML=stack-travis.yaml
  - stack update
install:
  - stack --no-terminal --skip-ghc-check setup
  - stack --no-terminal --skip-ghc-check test --only-snapshot
  # install jinja2
  - pip3 install --user Jinja2
  # install stack-hpc-coveralls
  - stack --no-terminal --skip-ghc-check install stack-hpc-coveralls || true

script:
  - stack --no-terminal --skip-ghc-check test --coverage
  - stack --no-terminal --skip-ghc-check sdist

  # check that the generated source-distribution can be built & installed
  #- export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}') ;
  #  (cd dist/;
  #  if [ -f "$SRC_TGZ" ]; then
  #    cabal install --force-reinstalls "$SRC_TGZ";
  #  else
  #    echo "expected '$SRC_TGZ' not found";
  #    exit 1;
  #  fi)

after_script:
  - shc haiji tests

# EOF
